name: Run MMA Scripts

on:
  workflow_dispatch:  # manual trigger
  schedule:
    - cron: '0 12 * * 1'  # monday noon

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUN_ONLY_CALCULATE_ELO: true  # Set to true to run only calculate_elo.py

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run get_links.py
        if: ${{ env.RUN_ONLY_CALCULATE_ELO != 'true' }}
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python get_links.py

      - name: Run get_fights.py
        if: ${{ env.RUN_ONLY_CALCULATE_ELO != 'true' }}
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python get_fights.py

      - name: Run calculate_elo.py
        if: ${{ env.RUN_ONLY_CALCULATE_ELO == 'true' }}
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python calculate_elo.py

      - name: Run scrape_ufc_ranks.py
        if: ${{ env.RUN_ONLY_CALCULATE_ELO == 'true' }}
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python scrape_ufc_ranks.py
